#!/bin/sh
set -e

# Xcode Cloud clones the repo fresh, so gitignored Secrets.xcconfig never exists on the
# runner. Without it, SUPABASE_ANON_KEY expands empty, AppConfiguration.isSupabaseConfigured
# is false, and every service factory silently falls back to mocks — the build "succeeds"
# but ships disconnected from the real backend.
#
# Requires these Environment Variables set on the Xcode Cloud workflow in App Store Connect
# (Secret, so they don't leak into logs): SUPABASE_ANON_KEY, GOOGLE_CLIENT_ID.

REPO_ROOT="$CI_PRIMARY_REPOSITORY_PATH"
SECRETS_FILE="$REPO_ROOT/Secrets.xcconfig"

if [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "warning: SUPABASE_ANON_KEY is not set in the Xcode Cloud workflow env vars — build will fall back to mocks."
fi

cat > "$SECRETS_FILE" <<EOF
// Generated by ci_post_clone.sh — do not edit, not committed.
SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY}
GOOGLE_CLIENT_ID = ${GOOGLE_CLIENT_ID}
EOF

echo "Wrote Secrets.xcconfig for Xcode Cloud build."
